springdoc:
  swagger-ui:
    path: "/bomber/swagger/swagger-ui.html"
  api-docs:
    path: "/bomber/swagger/v3/api-docs"


nats:
  spring:
    server: 25.53.4.151:4222
spring:
  data:
    mongodb:
      host: 172.17.0.2
      port: 27017
      database: bomber
  cloud:
    stream:
      defaultBinder: nats
      bindings:
        resultchannel:
          destination: bombers.server.task_result
          binder: nats
        taskchannel:
          destination: bombers.tasks.b746115b-78e8-4b79-bb93-33bc56047e7d
          binder: nats
        devicechannel:
          destination: bombers.server.init_bomber
          binder: nats