springdoc:
  swagger-ui:
    path: "/bomber/swagger/swagger-ui.html"
  api-docs:
    path: "/bomber/swagger/v3/api-docs"

org:
  bomber:
    team:
      arango:
        enabled: true
        host: arango-bomber
        database: test