springdoc:
  swagger-ui:
    path: "/bomber/swagger/swagger-ui.html"
  api-docs:
    path: "/bomber/swagger/v3/api-docs"


nats:
  spring:
    server:


spring:
  data:
    mongodb:
      host: 172.17.0.2
      port: 27017
      database: bomber
  cloud:
    stream:
      bindings:
        input:
          destination: dataIn
          binder: nats
        output:
          destination: dataOut
          binder: nats